package chap14_exception;

public class _02_generateException {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
			ArrayIndexOutOfBoundsException aie = 
					new ArrayIndexOutOfBoundsException("인덱스가 초과됐습니다.");
			throw aie;
		}catch(NullPointerException ne) {
			
		}catch(ArithmeticException ae) {
			
		}catch(Exception e) {
			
		}
	}

}
